# Generated by Django 5.0 on 2024-02-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='usename',
            new_name='username',
        ),
    ]
