# Generated by Django 5.0 on 2024-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_app', '0002_rename_usename_signupmodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=2912)),
                ('cate', models.CharField(max_length=2912)),
                ('myfile', models.FileField(upload_to='Notes_File')),
                ('dsc', models.TextField()),
            ],
        ),
    ]
